config/routes.rb
Shout::Application.routes.draw do
  get "static/home"
  get "static/help"
  get "static/about"
  get "static/contact"
  get "static/shapes"

 resources :posts
 resources :sessions, only: [:new, :create]
 
 root to: "static#home"

  match "/help",    to: 'static#help',          via: :get
  match "/about",   to: 'static#about',         via: :get
  match "/contact", to: 'static#contact',       via: :get
 	match "/shapes", 	to: 'static#shapes', 				via: :get
 	match "/signin", 	to: 'sessions#new', 				via: :get

end

app/views/shared/_cheatsheet.slim
div.cheatsheet
	table cellpadding="10" style="font-size:14;"
		/ tr
		/ 	th colspan="3" style="font-size:2em;color:gray;font-weight:normal;"
		/ 		| The Rules
		tr title="write anything, it just shows normally"
			td 
				div.plain
					| a
			td.arrow
				| →					
			td
				| a
		tr title="#{exaplain_backticks}"
			td style="padding-left:10px;"
				div.mark
				  | `2
				div.plain
					|  a
				div.mark
				  | `			
			td.arrow
				| →						  	
			td
				div style="font-size:2em;"
					|  a		
		tr title="You can go crazy big, and use any symbol"
			td
				div.mark
				  | `4
				div.plain
					|  a♥
				div.mark
				  | `		
			td.arrow
				| →						  		
			td
				div style="font-size:4em;"
					|  a♥		
		tr title="Wrap in backticks and append a valid internet address after a pipe symbol to link to a page on the internet"
			td colspan="2"
				div.mark
				  | `2
				div.plain
					|  goo 
				div.mark
				  | |
				div.mark
				  |  http://..com
				div.mark
				  | `		
				div.smallarrow
					| →						  
			td
				div style="font-size:2em;"
					a href="http://bit.ly/2V6CFi"
						| goo
		tr
			td colspan="3" style="color:#333;text-align: left;"
				= cheatsheet_text
				br
				= link_to shapes_text, shapes_path 

app/views/shared/_errors.slim
- error_array=object.errors.full_messages.delete_if {|m| m=~/digest/}
- if error_array.any?
  #error_explanation
    .alert.alert-error
       ul
        - error_array.each do |msg|
          li
            | *#{msg}

app/views/shared/_paginate.slim
= will_paginate collection, inner_window:pad, outer_window:pad, previous_label: '-', next_label: '+', id: id, param_name: id+'_page'

app/views/shared/_paginate_with_counter.slim
table cellpadding="5"
  tr
    td
      = render 'shared/paginate',collection: collection, pad: pad, id: id
  tr
    td
      = render 'shared/search_counter'

app/views/shared/_preview.slim
.big id=("preview")
  / = wrap(post.content)
  - if !post.content.blank?
  	= raw(mark(post.content))

app/views/shared/_search_counter.html.erb
<% search_count = @search_results.count  %>				
<% full_count = Post.published.count %>
<div id="counter">
	<%= "(" %>
	<%= full_count %>
	<%= "of them )" if search_count==full_count %> 
	<%= "of which #{search_count} match \'#{params[:search]}\' )" unless search_count==full_count %> 
</div>

app/views/shared/_search_fields.html.erb
<%= form_tag request.fullpath, class: "form-inline", method: 'get' do %>           
  <table cellpadding="5">
    <tr>
      <td>
        <%= text_field_tag :search,params[:search], 
        id: 'search', class: "input-large search-query" %>          
      </td>
      <td>
        <%= submit_tag "Search",
         id: "mp_search_button", class: "btn btn-primary btn-align" %>          
      </td>
      <td>
        <%= submit_tag "Clear",
         id: "mp_clear_search_button", class: "btn btn-primary btn-align" %>    
      </td>
    </tr>        
  </table>
<% end %>   

app/views/shared/_sidebar.slim
= render 'layouts/flash'
p.stream_title
	| recent
div#stream
	ul
		= render partial: 'posts/tile', collection: @posts, locals: {name: 'search', zoom: @zoom}
p.cheatsheet_title
	| cheatsheet		
div#cheatsheet
	= render partial: 'shared/cheatsheet'

app/views/shared/_welcome.slim
.opaque
.shiny
.center#catchy
	= catch_phrase
.center#elevator
	= elevator_pitch
.homebuttons
	ul.center 
		li = link_to signin_button_title, signin_path, id: 'signinbutton', class: "btn btn-primary" 
		li = link_to new_title, new_post_path, id: 'newbutton', class: "btn btn-warning" 
		li = link_to index_title, posts_path, id: 'indexbutton', class: "btn btn-success" 