config/routes.rb
Shout::Application.routes.draw do
  get "static/home"
  get "static/help"
  get "static/about"
  get "static/contact"
  get "static/shapes"

 resources :posts
 resources :sessions, only: [:new, :create]
 
 root to: "static#home"

  match "/help",    to: 'static#help',          via: :get
  match "/about",   to: 'static#about',         via: :get
  match "/contact", to: 'static#contact',       via: :get
 	match "/shapes", 	to: 'static#shapes', 				via: :get
 	match "/signin", 	to: 'sessions#new', 				via: :get

end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :integer          not null, primary key
#  content    :text
#  created_at :datetime
#  updated_at :datetime
#  published  :boolean          default(FALSE)
#  location   :string(255)
#

class Post < ActiveRecord::Base
	
	validates :content, length:  { minimum: 2 }
  default_scope -> { order('created_at DESC') }
  # scope :sort, -> { order('created_at DESC') }
  scope :published, -> {where(published: true)}
  scope :previewed, -> {where(published: false)}
  before_save { |post| post.content = post.content[0..2545].split("​").join } # 67*38

  def self.publication_tail(n=4)
  	published.sort_by! {|p| p.created_at}.reverse.first(n)
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_filter :no_edit, only: [:edit,:update]
  before_filter :set_location

  def new
    @title=new_title
    @post=Post.new 
    @posts=Post.publication_tail
    @zoom="small"
  end

  def create
    # binding.pry
    @title=new_title
  	@post=Post.new(post_params)
    @post.location=@location
    @posts=Post.publication_tail
    @zoom="small"    
    if @post.save
      fork(@post)
    else
      render 'new'      
    end
  end 

  def edit
    @title=edit_title
    @post=Post.find(params[:id])
    @post.location=@location
    @posts=Post.publication_tail
    @zoom="small"
  end

  def update
    @title=edit_title
    @post=Post.find(params[:id])
    @post.location=@location
    @posts=Post.publication_tail
    @zoom="small"    
    if @post.update_attributes(post_params)
      fork(@post)
    else
      render 'edit'      
    end
  end 

  def show
    @title=show_title
    @post=Post.find(params[:id]) 
  end

  def index 
    @title=index_title
    @search_zoom="tiny"
    @local_zoom="tiny"
    @all_posts=Post.published.to_a
    @search_results=search_stream(params[:search], Post.published)
    @local_results=local_stream(@location, Post.published) 
    # binding.pry
    @search_count=set_tile_count(@location)
    @local_count=@search_count
    # set_search_zoom unless params[:search].nil?
    @posts=@search_results.paginate(page: params[:search_page], 
      per_page: @search_count).order('created_at DESC')
    @local_posts=@local_results.paginate(page: params[:local_page], 
      per_page: @local_count).order('created_at DESC') unless @local_results.nil?
    redirect_to posts_path if params[:commit]=='Clear'
  end

	private

	  def post_params
      params.require(:post).permit(:content)
    end

    def search_stream(space_separated_search_terms, stream)    
      if !space_separated_search_terms.blank?      
        stream.where(generate_sql(space_separated_search_terms, 'content location',Post))
      else
        stream
      end
    end

    def local_stream(location, stream) 
      if !location.blank?      
        stream.where(generate_exact_sql(location, 'location',Post))
      end
    end  

    def fork(post)
      if params[:commit]==preview_button_title
        redirect_to edit_post_path(post)
      else
        post.toggle!(:published) unless post.published
        flash[:success] = "Thanks for sharing"                
        redirect_to new_post_path      
      end
    end

    def no_edit
      post = Post.find_by_id(params[:id])
      redirect_to new_post_path if post.nil? || post.published? 
    end

    def set_search_zoom
      @search_zoom = "medium" 
      @search_count = 4
    end

    def set_tile_count(location)
      if location.blank?
        return tile_count(1)
      else
        return tile_count(2)
      end
    end

end

app/helpers/posts_helper.rb
module PostsHelper

  def max_length
    67 
    #this seems to be the number of medium size a's that fit into 40em textarea width
  end
  def new_wrap(content)    
    array=replace_newline_with_br(content).split
    new_array=array.map do |string|
      smart_wrap(string)
    end
    sanitize(new_array.join(' '))
  end

  def wrap(content)    
    array=replace_newline_with_br(content).split
    new_array=array.map do |string|
      smart_wrap(string)
    end
    raw(new_array.join(' '))
  end

  def replace_newline_with_br(string)
    string.strip.gsub("\r\n","<br/>").gsub("\n", "<br/>").gsub("\r","<br/>")
  end

  def wrap_long_string(text, width = max_length)
    zero_width_space = "&#8203;"
    regex = /.{1,#{width}}/
    (text.length < width) ? text : 
                                text.scan(regex).join(zero_width_space)
  end

  def smart_wrap(text)
    array=text.split("<br/>")
    new_array =  array.map do |string|
      wrap_long_string(string)
    end
    new_array.join("<br/>")
  end  

  private



end

app/views/posts/_edit_post.slim
= form_for(@post) do |f|
	table cellpadding="9px" align="center"
		tr
			th.box_title valign="top"	
				| Edit
			th.box_title valign="top"	
				| Preview				
		tr
			td valign="top"
				= f.text_area :content, Xplaceholder: post_place_holder, id: :inputbox
			td valign="top"
				= render 'shared/preview', post: @post
		tr
			td align="center" 
				= f.submit preview_button_title,  id: "preview_button", class: "btn btn-large btn-success btn-long"	
			td align="center"
				- if @post.valid?				
					= f.submit publish_button_title, id: "publish_button", class: "btn btn-large btn-danger btn-long"
		tr
			td 
				= render 'shared/errors', object: f.object

app/views/posts/_new_post.slim
= form_for(@post) do |f|
	/ = render 'shared/errors', object: f.object
	table cellpadding="10px" align="center"
		tr
			th.box_title valign="top"	
				/ = post_place_holder
		tr
			td valign="top"
				= f.text_area :content, Xplaceholder: post_place_holder, id: :inputbox
		tr
			td align="center" 
				= f.submit preview_button_title,  id: "preview_button", class: "btn btn-large btn-success btn-long"	
		tr
			td 
				= render 'shared/errors', object: f.object

app/views/posts/_tile.html.erb
<li class="tile" id="<%= name+'_tile_'+tile.id.to_s %>">
	<%= link_to (render 'posts/tile_content', tile: tile, zoom: zoom), post_path(tile), id: "#{name}_link_#{tile.id}" %>
</li>

app/views/posts/_tile_content.slim
div class=(zoom) id=(tile.id) title=metadata(tile)
  = raw(mark(tile.content,"no_links"))

app/views/posts/create.slim
h1 Posts#create
p Find me in app/views/posts/create.html.erb

app/views/posts/edit.slim
div.row
	aside.span5#help
		= render 'shared/sidebar' 	
	aside.span2
		div.center
			= render 'posts/edit_post'			

app/views/posts/index.html.erb
<section>
	<div class="row">
		<table>
			<tr id="index_titles">
				<th>
					<div id='search_title'><%= search_title %><%= render 'shared/search_counter' %><div>
				</th>
				<% unless @location.blank? %>
					<th>
						<div id='local_title'>Local posts from <%= @location %></div>
					</th>				
				<% end %>
			</tr>
			<tr>
				<td id="search_stream">
					<ul>
						<% if @posts.to_a.any? %>
							<%= render partial: 'tile', collection: @posts, locals: {name: 'search', zoom: @search_zoom} %>
						<% else %>
							<%= no_posts_message %>
						<% end %>
					</ul>						
				</td>
				<% unless @location.blank? %>
				<td id="local_stream">
					<ul>
						<% if @local_posts.to_a.any? %>
							<%= render partial: 'tile', collection: @local_posts, locals: {name: 'local', zoom: @local_zoom} %>
						<% else %>
							<%= no_local_posts_message + @location %>
						<% end %>
					</ul>
				</td>
				<% end %>
			</tr>
			<tr>
				<td>
					<table class="full">
						<tr>
							<td class="center up" id="search_paginate">
								<%=  render 'shared/paginate', pad: 2, collection: @posts, id: 'search' %>			
							</td>
							<td class="right" id="search_panel">
								<%= render 'shared/search_fields' %>
							</td>
						</tr>
					</table>
				</td>
				<% unless @location.nil? %>
					<td class="center up" id="search_paginate">
						<%= render 'shared/paginate', pad: 2, collection: @local_posts, id: 'local' unless @local_posts.nil? %>
					</td>				
				<% end %>
			</tr>			
		</table>
	</div>
</section>

app/views/posts/new.slim
div.row
	aside.span5#sidebar
		= render 'shared/sidebar' 	
	aside.span2
		div.center
			= render 'posts/new_post'			

app/views/posts/show.slim
div.show
	table align="center"
		tr
			td 
				= render 'shared/preview', post: @post
				p.metadata title="Posted on #{@post.created_at}"
					= metadata(@post)