config/routes.rb
Shout::Application.routes.draw do
  get "static/home"
  get "static/help"
  get "static/about"
  get "static/contact"
  get "static/shapes"

 resources :posts
 resources :sessions, only: [:new, :create]
 
 root to: "static#home"

  match "/help",    to: 'static#help',          via: :get
  match "/about",   to: 'static#about',         via: :get
  match "/contact", to: 'static#contact',       via: :get
 	match "/shapes", 	to: 'static#shapes', 				via: :get
 	match "/signin", 	to: 'sessions#new', 				via: :get

end

app/views/layouts/_flash.html.erb
	<% flash.each do |key, value| %>		
		 <%= content_tag(:div, value, class: "alert alert-#{key}") %>
	<% end %>

app/views/layouts/_footer.slim
footer.footer
  nav
  	ul
  		li = link_to 'About', about_path
  		li = link_to 'Contact', contact_path
  		li = link_to 'Help', help_path
		

app/views/layouts/_header.slim
- if @location.blank?
	-	signin_link=wrap_location(signin_button_title)
- else 
	- signin_link=wrap_location(@location)

header.navbar.navbar-fixed-top.navbar-inverse
  .navbar-inner
    .container
      = link_to app_title, root_path, id: "logo"
      = link_to signin_link, signin_path, id: "location", title: "Change location" 
      nav
        ul#head-links.nav.pull-right
          li= link_to new_title, new_post_path        
          li= link_to index_title, posts_path

app/views/layouts/_includes.html.erb
  <%= stylesheet_link_tag "application", media: "all", 
  							"data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>  

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.slim
doctype
html
  head
    title
      = full_title(@title)
    = render 'layouts/includes'
    = render 'layouts/shim'
  body class=(params[:controller])
    = render 'layouts/header'
    .container
      = yield
    = render 'layouts/footer'